### PR TITLE
update base datascience-python version to v6.2.1

### PR DESCRIPTION
**Pull request by mheilman**
related to https://github.com/civisanalytics/datascience-python/pull/78

I tested this with a local image, and the API client seemed to work just fine.

### CODE REVIEW

**Comment by mheilman** [comment]
@jacksonllee, any idea why the CI test status is stuck?

**Comment by jacksonllee** [comment]
Screen Shot 2020-04-23 at 4 18 16 PM

No idea. It looks as if the CircleCI build has passed, but somehow GitHub didn't get that message? Might be related to the current (?) GitHub outrage (https://www.githubstatus.com/), but not sure.

**Comment by mheilman** [comment]
retrying the workflow (again) since github seems fine now

**Comment by mheilman** [comment]
@Icehawk78, hey, i just realized I should have tagged you on this since it's notebooks/firefly-related. Is it cool if I go ahead and publish a 6.2.1 release?

**Comment by Icehawk78** [comment]
Yep, all good for release

**Pull request merged**
